# Generated by Django 2.2.1 on 2019-07-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pswd', models.CharField(max_length=256)),
                ('cookie_id', models.CharField(max_length=256)),
                ('cookie_create_time', models.TimeField()),
                ('cookie_period', models.IntegerField()),
            ],
        ),
    ]
