# Generated by Django 2.2.3 on 2019-07-16 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubAnnouncements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField()),
                ('content', models.CharField(max_length=100)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubannouncement_publisher', to='people.User_info')),
            ],
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='pronounces',
        ),
        migrations.DeleteModel(
            name='ClubPronounces',
        ),
        migrations.AddField(
            model_name='organizations',
            name='announcements',
            field=models.ManyToManyField(related_name='organization_announcements', to='people.ClubAnnouncements'),
        ),
    ]
