# Generated by Django 2.2.1 on 2019-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cookie_create_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
