# Generated by Django 2.2.1 on 2019-07-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190710_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cookie_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
