# Generated by Django 2.2.3 on 2019-07-16 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_organizations_pending_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='pending_members',
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_message', models.CharField(default='', max_length=100)),
                ('apply_time', models.DateTimeField(blank=True, null=True)),
                ('application_status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'APPROVED'), (2, 'DENIED')], default=0)),
                ('solve_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('reply_message', models.CharField(default='', max_length=100)),
                ('inner_status_organization_exist', models.BooleanField(default=True)),
                ('inner_status_applicant_exist', models.BooleanField(default=True)),
                ('inner_status_solver_exist', models.BooleanField(default=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='membershipapplication_applicant', to='people.User_info')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='membershipapplication_org', to='people.Organizations')),
                ('solver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='membershipapplication_solver', to='people.User_info')),
            ],
        ),
    ]
