# Generated by Django 2.2.1 on 2019-07-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190710_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cookie_period',
        ),
        migrations.AddField(
            model_name='person',
            name='cookie_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cookie_create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
