# Generated by Django 2.2.3 on 2019-07-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190716_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='create_status',
            field=models.IntegerField(choices=[(0, '审核中'), (1, '已通过'), (2, '审核失败')], default=0),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='application_status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'APPROVED'), (2, 'DENIED'), (3, 'QUIT'), (4, 'EXPELLED')], default=0),
        ),
    ]
