# Generated by Django 2.2.1 on 2019-07-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20190711_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='organizations',
            fields=[
                ('number', models.BigAutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=30)),
                ('creater', models.CharField(max_length=30)),
                ('manager', models.CharField(max_length=30)),
                ('member', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(max_length=100)),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1)),
                ('birth_year', models.IntegerField(default=2019)),
                ('birth_month', models.SmallIntegerField(default=12)),
                ('birth_date', models.DateField()),
                ('profile', models.ImageField(upload_to='')),
                ('name', models.ForeignKey(on_delete='on_delete=models.CASCADE()', to='people.Person')),
            ],
        ),
    ]
