# Generated by Django 2.2.3 on 2019-07-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_organizations_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='sex',
        ),
        migrations.AddField(
            model_name='user_info',
            name='gender',
            field=models.IntegerField(choices=[(0, 'unknow'), (1, 'male'), (2, 'female')], default=0),
        ),
    ]
