# Generated by Django 2.2.3 on 2019-07-13 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20190712_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='birth_year',
        ),
        migrations.AlterField(
            model_name='organizations',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization1', to='people.User_info'),
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='member',
        ),
        migrations.AddField(
            model_name='organizations',
            name='member',
            field=models.ManyToManyField(related_name='organization2', to='people.User_info'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='birth_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
