# Generated by Django 2.2.3 on 2019-07-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20190713_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
