# Generated by Django 2.2.3 on 2019-07-13 04:23

from django.db import migrations, models
import django.db.models.deletion
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20190713_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='profile',
            field=models.ImageField(null=True, upload_to=people.models.user_logo_path),
        ),
    ]
